framework:
    messenger:
        transports:
            pimcore_core: "%env(RABBITMQ_URL)%/%2f/pimcore_core"
            pimcore_maintenance: "%env(RABBITMQ_URL)%/%2f/pimcore_maintenance"
            pimcore_scheduled_tasks: "%env(RABBITMQ_URL)%/%2f/pimcore_scheduled_tasks"
            pimcore_image_optimize: "%env(RABBITMQ_URL)%/%2f/pimcore_image_optimize"
            pimcore_asset_update: "%env(RABBITMQ_URL)%/%2f/pimcore_asset_update"
            ## When enabling additional transports, make sure to also enable the corresponding consumers in applicatons.yaml workers section ##
            # pimcore_job_execution_engine: "%env(RABBITMQ_URL)%/%2f/pimcore_job_execution_engine"
            # pimcore_data_import: "%env(RABBITMQ_URL)%/%2f/pimcore_data_import"
            # pimcore_datahub_fileexport: "%env(RABBITMQ_URL)%/%2f/pimcore_datahub_fileexport"
            # pimcore_generic_data_index_queue: "%env(RABBITMQ_URL)%/%2f/pimcore_generic_data_index_queue"
            # portal-engine-async: "%env(RABBITMQ_URL)%/%2f/portal-engine-async" 
            # pimcore_alternative_element_trees: "%env(RABBITMQ_URL)%/%2f/pimcore_alternative_element_trees"
            # pimcore_data_quality_management: "%env(RABBITMQ_URL)%/%2f/pimcore_data_quality_management"
            # pimcore_generic_execution_engine: "%env(RABBITMQ_URL)%/%2f/pimcore_generic_execution_engine"
            # pimcore_datahub_webhooks: "%env(RABBITMQ_URL)%/%2f/pimcore_datahub_webhooks" 
            # pimcore_search_backend_message: "%env(RABBITMQ_URL)%/%2f/pimcore_search_backend_message"
            # scheduler_generic_data_index: "%env(RABBITMQ_URL)%/%2f/scheduler_generic_data_index"

