monolog:
    handlers:
        main:
            type:  stream
            path:  "php://stdout"
            level: error
        error:
            type: stream
            path: "php://stdout"
            level: error
        console:
            type: console
            process_psr_3_messages: false