
SET NAMES utf8mb4;

INSERT INTO documents_page (`id`,`controller`,`template`,`title`,`description`,`prettyUrl`,`contentMainDocumentId`,`targetGroupIds`,`missingRequiredEditable`,`staticGeneratorEnabled`,`staticGeneratorLifetime`) VALUES (1,'App\\Controller\\ContentController::portalAction',NULL,'','',NULL,NULL,'',NULL,NULL,NULL);
INSERT INTO documents_page (`id`,`controller`,`template`,`title`,`description`,`prettyUrl`,`contentMainDocumentId`,`targetGroupIds`,`missingRequiredEditable`,`staticGeneratorEnabled`,`staticGeneratorLifetime`) VALUES (3,'App\\Controller\\DefaultController::defaultAction',NULL,'','',NULL,NULL,'',NULL,NULL,NULL);
INSERT INTO documents_page (`id`,`controller`,`template`,`title`,`description`,`prettyUrl`,`contentMainDocumentId`,`targetGroupIds`,`missingRequiredEditable`,`staticGeneratorEnabled`,`staticGeneratorLifetime`) VALUES (12,'App\\Controller\\DefaultController::defaultAction','includes/footer.html.twig','Pimcore Footer','',NULL,NULL,'',NULL,NULL,NULL);
INSERT INTO documents_page (`id`,`controller`,`template`,`title`,`description`,`prettyUrl`,`contentMainDocumentId`,`targetGroupIds`,`missingRequiredEditable`,`staticGeneratorEnabled`,`staticGeneratorLifetime`) VALUES (14,'App\\Controller\\DefaultController::defaultAction',NULL,'','',NULL,NULL,'',NULL,NULL,NULL);
INSERT INTO documents_page (`id`,`controller`,`template`,`title`,`description`,`prettyUrl`,`contentMainDocumentId`,`targetGroupIds`,`missingRequiredEditable`,`staticGeneratorEnabled`,`staticGeneratorLifetime`) VALUES (47,'App\\Controller\\ContentController::defaultAction',NULL,'','',NULL,NULL,'',NULL,0,NULL);
INSERT INTO documents_page (`id`,`controller`,`template`,`title`,`description`,`prettyUrl`,`contentMainDocumentId`,`targetGroupIds`,`missingRequiredEditable`,`staticGeneratorEnabled`,`staticGeneratorLifetime`) VALUES (88,'App\\Controller\\ContentController::defaultAction',NULL,'','',NULL,NULL,'',NULL,1,NULL);
INSERT INTO documents_page (`id`,`controller`,`template`,`title`,`description`,`prettyUrl`,`contentMainDocumentId`,`targetGroupIds`,`missingRequiredEditable`,`staticGeneratorEnabled`,`staticGeneratorLifetime`) VALUES (136,'App\\Controller\\ContentController::portalAction','','','',NULL,NULL,'',NULL,NULL,NULL);
INSERT INTO documents_page (`id`,`controller`,`template`,`title`,`description`,`prettyUrl`,`contentMainDocumentId`,`targetGroupIds`,`missingRequiredEditable`,`staticGeneratorEnabled`,`staticGeneratorLifetime`) VALUES (140,'App\\Controller\\ContentController::defaultAction',NULL,'','',NULL,47,'',NULL,NULL,NULL);
INSERT INTO documents_page (`id`,`controller`,`template`,`title`,`description`,`prettyUrl`,`contentMainDocumentId`,`targetGroupIds`,`missingRequiredEditable`,`staticGeneratorEnabled`,`staticGeneratorLifetime`) VALUES (160,'App\\Controller\\ContentController::defaultAction',NULL,'','',NULL,88,'',NULL,NULL,NULL);
INSERT INTO documents_page (`id`,`controller`,`template`,`title`,`description`,`prettyUrl`,`contentMainDocumentId`,`targetGroupIds`,`missingRequiredEditable`,`staticGeneratorEnabled`,`staticGeneratorLifetime`) VALUES (170,'App\\Controller\\DefaultController::defaultAction','includes/footer.html.twig','Pimcore Footer','',NULL,NULL,'',NULL,NULL,NULL);
INSERT INTO documents_page (`id`,`controller`,`template`,`title`,`description`,`prettyUrl`,`contentMainDocumentId`,`targetGroupIds`,`missingRequiredEditable`,`staticGeneratorEnabled`,`staticGeneratorLifetime`) VALUES (198,'App\\Controller\\ContentController::defaultAction',NULL,'','',NULL,NULL,'',NULL,NULL,NULL);
