
SET NAMES utf8mb4;

INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (1,'document','/','footer','document','12',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (1,'document','/','language','text','en',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (1,'document','/','left_nav_show','bool','',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (1,'document','/','left_nav_start_node','document','3',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (1,'document','/','navigation_accesskey','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (1,'document','/','navigation_anchor','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (1,'document','/','navigation_class','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (1,'document','/','navigation_exclude','bool','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (1,'document','/','navigation_name','text','home',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (1,'document','/','navigation_parameters','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (1,'document','/','navigation_relation','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (1,'document','/','navigation_root','document','3',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (1,'document','/','navigation_tabindex','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (1,'document','/','navigation_target','text',NULL,0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (1,'document','/','navigation_title','text','Oldimer Cars',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (1,'document','/','newsletter_confirm_mail','document','105',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (1,'document','/','news_default_document','document','65',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (1,'document','/','password_reset_mail','document','93',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (1,'document','/','terms_and_conditions','document','88',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (3,'document','/en','navigation_accesskey','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (3,'document','/en','navigation_anchor','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (3,'document','/en','navigation_class','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (3,'document','/en','navigation_exclude','bool','1',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (3,'document','/en','navigation_name','text','en',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (3,'document','/en','navigation_parameters','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (3,'document','/en','navigation_relation','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (3,'document','/en','navigation_tabindex','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (3,'document','/en','navigation_target','text',NULL,0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (3,'document','/en','navigation_title','text','Oldimer Cars',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (3,'document','/en','news_default_document','document','65',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (3,'document','/en','sidebar','document','36',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (3,'document','/en','terms_and_conditions','document','88',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (12,'document','/en/shared/includes/footer','navigation_name','text','footer',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (47,'document','/en/Getting Started','navigation_accesskey','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (47,'document','/en/Getting Started','navigation_anchor','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (47,'document','/en/Getting Started','navigation_class','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (47,'document','/en/Getting Started','navigation_exclude','bool','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (47,'document','/en/Getting Started','navigation_name','text','Getting Started',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (47,'document','/en/Getting Started','navigation_parameters','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (47,'document','/en/Getting Started','navigation_relation','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (47,'document','/en/Getting Started','navigation_tabindex','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (47,'document','/en/Getting Started','navigation_target','text',NULL,0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (47,'document','/en/Getting Started','navigation_title','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (47,'document','/en/Getting Started','root_category','object','564',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (78,'document','/print/Demo-Catalog/Muscle Cars','print_register_title','text','Muscle Cars',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (78,'document','/print/Demo-Catalog/Muscle Cars','print_register_type','select','orange',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (80,'document','/print/Demo-Catalog/British Sports Cars','print_register_title','text','British Sports Cars',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (80,'document','/print/Demo-Catalog/British Sports Cars','print_register_type','select','green',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (83,'document','/print/Demo-Catalog/German Cars','print_register_title','text','German Luxury Cars',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (83,'document','/print/Demo-Catalog/German Cars','print_register_type','select','blue',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (88,'document','/en/Getting Started/Start-Your-PimCore-AI-Project','navigation_accesskey','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (88,'document','/en/Getting Started/Start-Your-PimCore-AI-Project','navigation_anchor','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (88,'document','/en/Getting Started/Start-Your-PimCore-AI-Project','navigation_class','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (88,'document','/en/Getting Started/Start-Your-PimCore-AI-Project','navigation_exclude','bool','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (88,'document','/en/Getting Started/Start-Your-PimCore-AI-Project','navigation_name','text','Next Steps',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (88,'document','/en/Getting Started/Start-Your-PimCore-AI-Project','navigation_parameters','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (88,'document','/en/Getting Started/Start-Your-PimCore-AI-Project','navigation_relation','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (88,'document','/en/Getting Started/Start-Your-PimCore-AI-Project','navigation_tabindex','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (88,'document','/en/Getting Started/Start-Your-PimCore-AI-Project','navigation_target','text',NULL,0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (88,'document','/en/Getting Started/Start-Your-PimCore-AI-Project','navigation_title','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (136,'document','/de','footer','document','170',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (136,'document','/de','language','text','de',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (136,'document','/de','left_nav_show','bool','',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (136,'document','/de','left_nav_start_node','document','136',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (136,'document','/de','navigation_accesskey','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (136,'document','/de','navigation_anchor','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (136,'document','/de','navigation_class','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (136,'document','/de','navigation_exclude','bool','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (136,'document','/de','navigation_name','text','Home',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (136,'document','/de','navigation_parameters','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (136,'document','/de','navigation_relation','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (136,'document','/de','navigation_root','document','136',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (136,'document','/de','navigation_tabindex','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (136,'document','/de','navigation_target','text',NULL,0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (136,'document','/de','navigation_title','text','Oldimer Cars',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (136,'document','/de','newsletter_confirm_mail','document','146',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (136,'document','/de','news_default_document','document','142',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (136,'document','/de','password_reset_mail','document','145',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (136,'document','/de','terms_and_conditions','document','160',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (140,'document','/de/Start','navigation_accesskey','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (140,'document','/de/Start','navigation_anchor','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (140,'document','/de/Start','navigation_class','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (140,'document','/de/Start','navigation_exclude','bool','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (140,'document','/de/Start','navigation_name','text','Start',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (140,'document','/de/Start','navigation_parameters','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (140,'document','/de/Start','navigation_relation','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (140,'document','/de/Start','navigation_tabindex','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (140,'document','/de/Start','navigation_target','text',NULL,0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (140,'document','/de/Start','navigation_title','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (140,'document','/de/Start','root_category','object','564',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (160,'document','/de/Start/Terms-and-Conditions','navigation_accesskey','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (160,'document','/de/Start/Terms-and-Conditions','navigation_anchor','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (160,'document','/de/Start/Terms-and-Conditions','navigation_class','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (160,'document','/de/Start/Terms-and-Conditions','navigation_exclude','bool','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (160,'document','/de/Start/Terms-and-Conditions','navigation_name','text','Terms and Conditions [EN]',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (160,'document','/de/Start/Terms-and-Conditions','navigation_parameters','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (160,'document','/de/Start/Terms-and-Conditions','navigation_relation','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (160,'document','/de/Start/Terms-and-Conditions','navigation_tabindex','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (160,'document','/de/Start/Terms-and-Conditions','navigation_target','text',NULL,0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (160,'document','/de/Start/Terms-and-Conditions','navigation_title','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (170,'document','/de/shared/includes/footer','navigation_name','text','footer',1);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (198,'document','/en/Error-Page','navigation_accesskey','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (198,'document','/en/Error-Page','navigation_anchor','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (198,'document','/en/Error-Page','navigation_class','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (198,'document','/en/Error-Page','navigation_exclude','bool','1',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (198,'document','/en/Error-Page','navigation_name','text','Error-Page',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (198,'document','/en/Error-Page','navigation_parameters','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (198,'document','/en/Error-Page','navigation_relation','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (198,'document','/en/Error-Page','navigation_tabindex','text','',0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (198,'document','/en/Error-Page','navigation_target','text',NULL,0);
INSERT INTO properties (`cid`,`ctype`,`cpath`,`name`,`type`,`data`,`inheritable`) VALUES (198,'document','/en/Error-Page','navigation_title','text','',0);
